### ISSUE TITLE
Added new miners and updated some

### ISSUE THREAD

**Issue by papampi** [papampi/nvOC_miners#4]
Added some miners and edited miner update script in 19-2.1 branch.
Forgot to make new branch and pull request so you can check easier.

Please when you get time, take a look and see if all is ok.
Thanks.

**Comment by LuKePicci** [comment]
Almost good, the only thing you have to fdo is remove all "version" file from the repo folders, they have to be only inside the binaries archive otherwise the version checking is broken. Meanwhile would be better to use xz compression instead of gz, it's way more efficient.

**Comment by Alysko** [comment]
Why not to add wget to each miner repo instead of making tar and include them in git?

**Comment by LuKePicci** [comment]
Because not all miner repos have tarballs, and there's no reason to depend on them. We only need the single executable binary, and most of them does not provide such kind of a tarball. Moreover, there is not a good point in the updating workflow where to perform the actual download. If you pull the updated git miners submodule you would then execute a further download script, before installing.

**Comment by LuKePicci** [comment]
And of course you would loose the ability to revert/switch to different branches of miners without having to implement such functionality with a smart combination of wget commands and old binary move/rename

**Comment by Alysko** [comment]
OK.
Line 166: cat ${NVOC_MINERS}/bminer/bminer-v8.0.0.tar.gz -> tar.xz

**Comment by LuKePicci** [comment]
Yup, there are a few other also.

**Comment by LuKePicci** [comment]
@papampi , because of a git limitation in submodule handling, shallow clones of submodules tracking a specific branch which is not the primary one does not work. We have to do one of the following things:
- make `19-2.1` the primary branch
- continue using `19-2.1` as a development branch and
  - merge that branch into `master` branch when needed
  - do the same on a new `release` branch an make it pramary

**Comment by papampi** [comment]
I think better to keep the master until the stable release of 19-2.1, then we merge 19-2.1 to master
Users may still want to install 19-2.0 and need to update miners from master repo. 
We can set 19-2.1 as primary for now

**Comment by LuKePicci** [comment]
Ok, let me know whan you did it, I will update the wiki as soon as I test it successfully.

**Comment by papampi** [comment]
19-2.1 is base branch

**Comment by LuKePicci** [comment]
Fine, now it works as expected, it only downloads latest versions while cloning with commands I previously wrote in the wiki page.
